title: Miguel Ferreira 
logo: "/images/miguelrferreiraf_data_scientist.jfif?raw=true" 
description: 
  <strong>Data Scientist | Machine Learning Engineer</strong>
  <br><br>
  I am a Production Engineering student deeply interested in Data Science, specially Machine Learning.
  <br><br>
  <a href="https://www.linkedin.com/in/miguel-r-ferreira/">View My Linkedin Profile</a>
   
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
